services:
  - type: web
    name: suxbat-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: TOKEN_SECRET_PASSWORD
        sync: false
      - key: BASE_URL
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: EMAIL
        sync: false
      - key: MAILING_ID
        sync: false
      - key: MAILING_SECRET
        sync: false
      - key: MAILING_REFRESH
        sync: false
