export const EMAIL_VERIFICATION_REQUEST = "EMAIL_VERIFICATION_REQUEST";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAIL = "EMAIL_VERIFICATION_FAIL";
export const EMAIL_VERIFICATION_RESET = "EMAIL_VERIFICATION_RESET";

export const EMAIL_VERIFICATION_LINK_SENT_REQUEST =
  "EMAIL_VERIFICATION_LINK_SENT_REQUEST";
export const EMAIL_VERIFICATION_LINK_SENT_SUCCESS =
  "EMAIL_VERIFICATION_LINK_SENT_SUCCESS";
export const EMAIL_VERIFICATION_LINK_SENT_FAIL =
  "EMAIL_VERIFICATION_LINK_SENT_FAIL";
export const EMAIL_VERIFICATION_LINK_SENT_RESET =
  "EMAIL_VERIFICATION_LINK_SENT_RESET";

export const PASSWORD_RESET_CODE_REQUEST = "PASSWORD_RESET_CODE_REQUEST";
export const PASSWORD_RESET_CODE_SUCCESS = "PASSWORD_RESET_CODE_SUCCESS";
export const PASSWORD_RESET_CODE_FAIL = "PASSWORD_RESET_CODE_FAIL";
export const PASSWORD_RESET_CODE_RESET = "PASSWORD_RESET_CODE_RESET";

export const VALIDATE_RESET_CODE_REQUEST = "VALIDATE_RESET_CODE_REQUEST";
export const VALIDATE_RESET_CODE_SUCCESS = "VALIDATE_RESET_CODE_SUCCESS";
export const VALIDATE_RESET_CODE_FAIL = "VALIDATE_RESET_CODE_FAIL";
export const VALIDATE_RESET_CODE_RESET = "VALIDATE_RESET_CODE_RESET";
