export const GROUP_CREATE_REQUEST = "GROUP_CREATE_REQUEST";
export const GROUP_CREATE_SUCCESS = "GROUP_CREATE_SUCCESS";
export const GROUP_CREATE_FAIL = "GROUP_CREATE_FAIL";
export const GROUP_CREATE_RESET = "GROUP_CREATE_RESET";

export const LIST_YOUR_GROUPS_REQUEST = "LIST_YOUR_GROUPS_REQUEST";
export const LIST_YOUR_GROUPS_SUCCESS = "LIST_YOUR_GROUPS_SUCCESS";
export const LIST_YOUR_GROUPS_FAIL = "LIST_YOUR_GROUPS_FAIL";

export const SEARCH_GROUP_REQUEST = "SEARCH_GROUP_REQUEST";
export const SEARCH_GROUP_SUCCESS = "SEARCH_GROUP_SUCCESS";
export const SEARCH_GROUP_FAIL = "SEARCH_GROUP_FAIL";

export const GROUP_JOIN_REQUEST = "GROUP_JOIN_REQUEST";
export const GROUP_JOIN_SUCCESS = "GROUP_JOIN_SUCCESS";
export const GROUP_JOIN_FAIL = "GROUP_JOIN_FAIL";

export const GROUP_LEAVE_REQUEST = "GROUP_LEAVE_REQUEST";
export const GROUP_LEAVE_SUCCESS = "GROUP_LEAVE_SUCCESS";
export const GROUP_LEAVE_FAIL = "GROUP_LEAVE_FAIL";
