export const MESSAGES_LIST_REQUEST = "MESSAGES_LIST_REQUEST";
export const MESSAGES_LIST_SUCCESS = "MESSAGES_LIST_SUCCESS";
export const MESSAGES_LIST_FAIL = "MESSAGES_LIST_FAIL";

export const MESSAGES_CREATE_REQUEST = "MESSAGES_CREATE_REQUEST";
export const MESSAGES_CREATE_SUCCESS = "MESSAGES_CREATE_SUCCESS";
export const MESSAGES_CREATE_FAIL = "MESSAGES_CREATE_FAIL";
export const MESSAGES_CREATE_RESET = "MESSAGES_CREATE_RESET";
