export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_REACT_REQUEST = "POST_REACT_REQUEST";
export const POST_REACT_SUCCESS = "POST_REACT_SUCCESS";
export const POST_REACT_FAIL = "POST_REACT_FAIL";
export const POST_REACT_RESET = "POST_REACT_RESET";

export const POST_GET_REACTS_REQUEST = "POST_GET_REACTS_REQUEST";
export const POST_GET_REACTS_SUCCESS = "POST_GET_REACTS_SUCCESS";
export const POST_GET_REACTS_FAIL = "POST_GET_REACTS_FAIL";

export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";

export const POST_SAVE_REQUEST = "POST_SAVE_REQUEST";
export const POST_SAVE_SUCCESS = "POST_SAVE_SUCCESS";
export const POST_SAVE_FAIL = "POST_SAVE_FAIL";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";
export const POST_DELETE_RESET = "POST_DELETE_RESET";
