export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const LIST_YOUR_PRODUCTS_REQUEST = "LIST_YOUR_PRODUCTS_REQUEST";
export const LIST_YOUR_PRODUCTS_SUCCESS = "LIST_YOUR_PRODUCTS_SUCCESS";
export const LIST_YOUR_PRODUCTS_FAIL = "LIST_YOUR_PRODUCTS_FAIL";

export const LIST_PRODUCTS_REQUEST = "LIST_PRODUCTS_REQUEST";
export const LIST_PRODUCTS_SUCCESS = "LIST_PRODUCTS_SUCCESS";
export const LIST_PRODUCTS_FAIL = "LIST_PRODUCTS_FAIL";

export const LIST_PRODUCTS_CATEGORIES_REQUEST =
  "LIST_PRODUCTS_CATEGORIES_REQUEST";
export const LIST_PRODUCTS_CATEGORIES_SUCCESS =
  "LIST_PRODUCTS_CATEGORIES_SUCCESS";
export const LIST_PRODUCTS_CATEGORIES_FAIL = "LIST_PRODUCTS_CATEGORIES_FAIL";

export const PRODUCT_FIND_REQUEST = "PRODUCT_FIND_REQUEST";
export const PRODUCT_FIND_SUCCESS = "PRODUCT_FIND_SUCCESS";
export const PRODUCT_FIND_FAIL = "PRODUCT_FIND_FAIL";
