export const IMAGES_UPLOAD_REQUEST = "IMAGES_UPLOAD_REQUEST";
export const IMAGES_UPLOAD_SUCCESS = "IMAGES_UPLOAD_SUCCESS";
export const IMAGES_UPLOAD_FAIL = "IMAGES_UPLOAD_FAIL";
export const IMAGES_UPLOAD_RESET = "IMAGES_UPLOAD_RESET";

export const IMAGES_COMMENT_UPLOAD_REQUEST = "IMAGES_COMMENT_UPLOAD_REQUEST";
export const IMAGES_COMMENT_UPLOAD_SUCCESS = "IMAGES_COMMENT_UPLOAD_SUCCESS";
export const IMAGES_COMMENT_UPLOAD_FAIL = "IMAGES_COMMENT_UPLOAD_FAIL";
export const IMAGES_COMMENT_UPLOAD_RESET = "IMAGES_COMMENT_UPLOAD_RESET";

export const IMAGES_LIST_REQUEST = "IMAGES_LIST_REQUEST";
export const IMAGES_LIST_SUCCESS = "IMAGES_LIST_SUCCESS";
export const IMAGES_LIST_FAIL = "IMAGES_LIST_FAIL";
