export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_FIND_REQUEST = "USER_FIND_REQUEST";
export const USER_FIND_SUCCESS = "USER_FIND_SUCCESS";
export const USER_FIND_FAIL = "USER_FIND_FAIL";

export const USER_PASSWORD_CHANGE_REQUEST = "USER_PASSWORD_CHANGE_REQUEST";
export const USER_PASSWORD_CHANGE_SUCCESS = "USER_PASSWORD_CHANGE_SUCCESS";
export const USER_PASSWORD_CHANGE_FAIL = "USER_PASSWORD_CHANGE_FAIL";
export const USER_PASSWORD_CHANGE_RESET = "USER_PASSWORD_CHANGE_RESET";

export const PROFILE_DETAILS_REQUEST = "PROFILE_DETAILS_REQUEST";
export const PROFILE_DETAILS_SUCCESS = "PROFILE_DETAILS_SUCCESS";
export const PROFILE_DETAILS_FAIL = "PROFILE_DETAILS_FAIL";

export const PROFILE_PICTURE_UPDATE_REQUEST = "PROFILE_PICTURE_UPDATE_REQUEST";
export const PROFILE_PICTURE_UPDATE_SUCCESS = "PROFILE_PICTURE_UPDATE_SUCCESS";
export const PROFILE_PICTURE_UPDATE_FAIL = "PROFILE_PICTURE_UPDATE_FAIL";
export const PROFILE_PICTURE_UPDATE_RESET = "PROFILE_PICTURE_UPDATE_RESET";

export const PROFILE_COVER_UPDATE_REQUEST = "PROFILE_COVER_UPDATE_REQUEST";
export const PROFILE_COVER_UPDATE_SUCCESS = "PROFILE_COVER_UPDATE_SUCCESS";
export const PROFILE_COVER_UPDATE_FAIL = "PROFILE_COVER_UPDATE_FAIL";
export const PROFILE_COVER_UPDATE_RESET = "PROFILE_COVER_UPDATE_RESET";

export const PROFILE_DETAILS_UPDATE_REQUEST = "PROFILE_DETAILS_UPDATE_REQUEST";
export const PROFILE_DETAILS_UPDATE_SUCCESS = "PROFILE_DETAILS_UPDATE_SUCCESS";
export const PROFILE_DETAILS_UPDATE_FAIL = "PROFILE_DETAILS_UPDATE_FAIL";
export const PROFILE_DETAILS_UPDATE_RESET = "PROFILE_DETAILS_UPDATE_RESET";

export const PROFILE_ADD_FRIEND_REQUEST = "PROFILE_ADD_FRIEND_REQUEST";
export const PROFILE_ADD_FRIEND_SUCCESS = "PROFILE_ADD_FRIEND_SUCCESS";
export const PROFILE_ADD_FRIEND_FAIL = "PROFILE_ADD_FRIEND_FAIL";
export const PROFILE_ADD_FRIEND_RESET = "PROFILE_ADD_FRIEND_RESET";

export const PROFILE_CANCEL_REQUEST_REQUEST = "PROFILE_CANCEL_REQUEST_REQUEST";
export const PROFILE_CANCEL_REQUEST_SUCCESS = "PROFILE_CANCEL_REQUEST_SUCCESS";
export const PROFILE_CANCEL_REQUEST_FAIL = "PROFILE_CANCEL_REQUEST_FAIL";
export const PROFILE_CANCEL_REQUEST_RESET = "PROFILE_CANCEL_REQUEST_RESET";

export const PROFILE_FOLLOW_REQUEST = "PROFILE_FOLLOW_REQUEST";
export const PROFILE_FOLLOW_SUCCESS = "PROFILE_FOLLOW_SUCCESS";
export const PROFILE_FOLLOW_FAIL = "PROFILE_FOLLOW_FAIL";
export const PROFILE_FOLLOW_RESET = "PROFILE_FOLLOW_RESET";

export const PROFILE_UNFOLLOW_REQUEST = "PROFILE_UNFOLLOW_REQUEST";
export const PROFILE_UNFOLLOW_SUCCESS = "PROFILE_UNFOLLOW_SUCCESS";
export const PROFILE_UNFOLLOW_FAIL = "PROFILE_UNFOLLOW_FAIL";
export const PROFILE_UNFOLLOW_RESET = "PROFILE_UNFOLLOW_RESET";

export const PROFILE_UNFRIEND_REQUEST = "PROFILE_UNFRIEND_REQUEST";
export const PROFILE_UNFRIEND_SUCCESS = "PROFILE_UNFRIEND_SUCCESS";
export const PROFILE_UNFRIEND_FAIL = "PROFILE_UNFRIEND_FAIL";
export const PROFILE_UNFRIEND_RESET = "PROFILE_UNFRIEND_RESET";

export const PROFILE_DELETE_FRIEND_REQUEST_REQUEST =
  "PROFILE_DELETE_FRIEND_REQUEST_REQUEST";
export const PROFILE_DELETE_FRIEND_REQUEST_SUCCESS =
  "PROFILE_DELETE_FRIEND_REQUEST_SUCCESS";
export const PROFILE_DELETE_FRIEND_REQUEST_FAIL =
  "PROFILE_DELETE_FRIEND_REQUEST_FAIL";
export const PROFILE_DELETE_FRIEND_REQUEST_RESET =
  "PROFILE_DELETE_FRIEND_REQUEST_RESET";

export const PROFILE_ACCEPT_FRIEND_REQUEST_REQUEST =
  "PROFILE_ACCEPT_FRIEND_REQUEST_REQUEST";
export const PROFILE_ACCEPT_FRIEND_REQUEST_SUCCESS =
  "PROFILE_ACCEPT_FRIEND_REQUEST_SUCCESS";
export const PROFILE_ACCEPT_FRIEND_REQUEST_FAIL =
  "PROFILE_ACCEPT_FRIEND_REQUEST_FAIL";
export const PROFILE_ACCEPT_FRIEND_REQUEST_RESET =
  "PROFILE_ACCEPT_FRIEND_REQUEST_RESET";

export const USER_SEARCH_REQUEST = "USER_SEARCH_REQUEST";
export const USER_SEARCH_SUCCESS = "USER_SEARCH_SUCCESS";
export const USER_SEARCH_FAIL = "USER_SEARCH_FAIL";

export const USER_ADD_SEARCH_HISTORY_REQUEST =
  "USER_ADD_SEARCH_HISTORY_REQUEST";
export const USER_ADD_SEARCH_HISTORY_SUCCESS =
  "USER_ADD_SEARCH_HISTORY_SUCCESS";
export const USER_ADD_SEARCH_HISTORY_FAIL = "USER_ADD_SEARCH_HISTORY_FAIL";

export const USER_GET_SEARCH_HISTORY_REQUEST =
  "USER_GET_SEARCH_HISTORY_REQUEST";
export const USER_GET_SEARCH_HISTORY_SUCCESS =
  "USER_GET_SEARCH_HISTORY_SUCCESS";
export const USER_GET_SEARCH_HISTORY_FAIL = "USER_GET_SEARCH_HISTORY_FAIL";

export const USER_REMOVE_SEARCH_HISTORY_REQUEST =
  "USER_REMOVE_SEARCH_HISTORY_REQUEST";
export const USER_REMOVE_SEARCH_HISTORY_SUCCESS =
  "USER_REMOVE_SEARCH_HISTORY_SUCCESS";
export const USER_REMOVE_SEARCH_HISTORY_FAIL =
  "USER_REMOVE_SEARCH_HISTORY_FAIL";

export const USER_GET_FRIENDS_INFO_REQUEST = "USER_GET_FRIENDS_INFO_REQUEST";
export const USER_GET_FRIENDS_INFO_SUCCESS = "USER_GET_FRIENDS_INFO_SUCCESS";
export const USER_GET_FRIENDS_INFO_FAIL = "USER_GET_FRIENDS_INFO_FAIL";

export const USER_SUGGEST_FRIENDS_REQUEST = "USER_SUGGEST_FRIENDS_REQUEST";
export const USER_SUGGEST_FRIENDS_SUCCESS = "USER_SUGGEST_FRIENDS_SUCCESS";
export const USER_SUGGEST_FRIENDS_FAIL = "USER_SUGGEST_FRIENDS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";
